// react/src/components/NavMenu.tsx
import {MenuItem} from "../../../common/models/menu-item.model.ts";
import {Container, Navbar} from "react-bootstrap";

interface NavMenuInterface {
    title: string;
    items: MenuItem[];
}

function NavMenu({ title, items }: NavMenuInterface) {
    return (
        <div className="padding-general">
            {title && <strong>{title}</strong>}
            {items && (
                <Navbar className="bg-body-tertiary">
                    {items.map(item => (
                        <Container key={item.id}>
                            <Navbar.Brand href={item.link}>
                                <span>{item.title}</span>
                                <br/>
                                {item.description && <small>{item.description}</small>}
                            </Navbar.Brand>
                        </Container>
                    ))}
                </Navbar>
            )}
        </div>
    );
}

export default NavMenu;

// angular-design-patterns/src/app/components/nav-menu/nav-menu.component.ts
import { Component, input } from '@angular/core';
import { MatListModule } from '@angular/material/list';
import { MenuItem } from '../../../../../common/models/menu-item.model';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'nav-menu',
  standalone: true,
  imports: [MatListModule, RouterModule,],
  templateUrl: './nav-menu.component.html',
  styleUrl: './nav-menu.component.scss'
})
export class NavMenuComponent {
  title = input<string|null>();
  items = input<MenuItem[]>();
}

<div class="padding-general">
  @if(title()) {
    <strong>{{title()}}</strong>
  }
  
  @if(items()) {
    <mat-list>
      @for(item of items(); track item.id) {
          <mat-list-item [routerLink]="item.link">
            <span matListItemTitle>{{item.title}}</span>
            @if(item.description) {
                <span matListItemLine>{{item.description}}</span>
            }
          </mat-list-item>
      }
    </mat-list>
  }
</div>
