// angular-design-patterns/src/app/components/info-goal/info-goal.component.ts
import { Component, input } from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { ProgressGoalComponent } from '../progress-goal/progress-goal.component';

@Component({
  selector: 'info-goal',
  standalone: true,
  imports: [MatCardModule, ProgressGoalComponent],
  templateUrl: './info-goal.component.html',
  styleUrl: './info-goal.component.scss'
})
export class InfoGoalComponent {
  name = input.required<string>();
  description = input.required();
  endDate = input.required<Date>();
  startDate = input.required<Date>();
  progress = input.required<number>();
}

<mat-card appearance="outlined">
    <mat-card-header>
        <div class="info-goal__wrapper--title">
            <mat-card-title>{{name()}}</mat-card-title>
            <div class="align-horizontally-center">
                <progress-goal [progress]="progress() || 0"></progress-goal>
                <span class="margin-left__1">
                    {{progress()}}% Complete
                </span>
            </div>
        </div>
    </mat-card-header>
    <mat-card-content>
      <div>
          {{description()}}
      </div>
    </mat-card-content>
  </mat-card>

// react/src/components/InfoGoal.tsx
import {Card, ProgressBar} from "react-bootstrap";

interface InfoGoalProps {
    name: string;
    progress: number;
    description: string;
    className?: string;
}

export default function InfoGoal({ name, progress, description, className }: InfoGoalProps) {
    return (
        <Card className={className}>
            <Card.Header>
                <div className="info-goal__wrapper--title">
                    <Card.Title>{name}</Card.Title>
                    <div className="align-horizontally-center">
                        <ProgressBar now={progress || 0} />
                        <span className="margin-left__1">
                                {progress}% Complete
                            </span>
                    </div>
                </div>
            </ Card.Header>
            <Card.Body>
                <div>
                    {description}
                </div>
            </Card.Body>
        </Card>
    );
};
